on:
  pull_request:
    types: [opened, synchronize]

name: Pull Request updated

jobs:
  triage:
    name: Pull Request Labeler
    runs-on: ubuntu-latest
    if: "! startsWith(github.event.pull_request.head.ref, 'release/')"
    steps:
      - name: Pull Request Labeler
        uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  history:
    name: Pull Request Body
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.head.ref, 'release/') || github.event.pull_request.head.user.id == github.event.pull_request.base.user.id
    steps:
      - name: Pull Request Body
        uses: technote-space/pr-commit-body-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXCLUDE_MESSAGES: |
            trigger workflow
            Update TOC
            Update package version
          TITLE: '## Changes'
          LINK_ISSUE_KEYWORD: ${{ (startsWith(github.event.pull_request.head.ref, 'release/') && 'closes') || '' }}
          FILTER_PR: true
